New branch
amaurycb/AppEmpty pull request #1
Opened 2020-07-22 05:55 UTC by amaurycb

2020-07-24 04:56 UTC, amaurycb commented
Todo listo

2020-07-27 06:55 UTC, williamgdev requested changes

2020-07-27 06:55 UTC, williamgdev commented on app/src/main/java/com/example/appempty/MainActivity.kt
> +        startActivity(intent)
You should use a fragment instead of another activity.

2020-07-27 06:55 UTC, williamgdev commented on app/src/main/java/com/example/appempty/PersonaActivity.kt
> +class PersonaActivity : AppCompatActivity() {
same here, this should be a Fragment

2020-07-27 06:55 UTC, williamgdev commented on app/src/main/java/com/example/appempty/Personas.kt
> +class Personas(val nombre: String, val username: String, val age: Int, val degree: Int) : Serializable
This should be Persona instead of Personas

2020-07-27 06:55 UTC, williamgdev commented on app/src/main/java/com/example/appempty/PersonaAdapter.kt
> +        val persona = listaPersonas[position]
persona should be personaList or something similar that will define a list

2020-07-27 06:55 UTC, williamgdev commented on app/src/main/res/layout/activity_persona.xml
> +        app:layout_constraintTop_toBottomOf="@+id/nombre_persona" />
good job on researching about ConstraintLayout

2020-07-29 04:35 UTC, closed without merging