View model
amaurycb/AppEmpty pull request #13
Opened 2020-08-22 03:36 UTC by amaurycb

2020-08-22 04:57 UTC, williamgdev requested changes

2020-08-22 04:57 UTC, williamgdev commented on app/src/main/java/com/example/appempty/SecondFragment.kt
> +       userViewModel.usuario.observe(this, androidx.lifecycle.Observer {
You should use lambda expressions
`userViewModel.usuario.observe(this, androidx.lifecycle.Observer { result ->`

2020-08-22 04:57 UTC, williamgdev commented on app/src/main/java/com/example/appempty/ViewModel/UserViewModel.kt
> + //  val userresult = MutableLiveData<List<UserProfile>>()
if you are not using it, please remove it.

2020-08-22 04:57 UTC, williamgdev commented on app/src/main/java/com/example/appempty/ViewModel/UserViewModel.kt
> +    fun loadUser(displayUserInfo: (UserProfile) -> Unit) {
How do you suppose to run the network call?
you have two options
1- Call the method when you load the Fragment
2- Here in the ViewModel call the method on the initialization 
`init {
loadUser()
}`

2020-08-22 04:57 UTC, williamgdev commented on app/src/main/java/com/example/appempty/ViewModel/UserViewModel.kt
> +                displayUserInfo(result)
You do not need the displayUserInfo method since you are observing the LiveData. In other words no need to return a value, just save the result in the livedata

2020-09-03 06:36 UTC, amaurycb commented
Comment deleted

2020-09-03 06:39 UTC, williamgdev approved these changes

2020-09-03 06:39 UTC, merged