Fragment details
amaurycb/AppEmpty pull request #7
Opened 2020-07-31 23:12 UTC by amaurycb

Done ufff

2020-08-02 19:06 UTC, williamgdev requested changes

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/java/com/example/appempty/SecondFragment.kt
> +private const val ARG_PARAM1 = "param1"
You are not using this two args, why not remove it.

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/java/com/example/appempty/SecondFragment.kt
> +    override fun onCreate(savedInstanceState: Bundle?) {
In case to remove the args you do not need this method

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/java/com/example/appempty/SecondFragment.kt
> +        fun newInstance(param1: String, param2: String) =
In case you remove the args you do not need this to params inside newInstance

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
why there are two fragments here, it should be only one. Or if you use navigation this activity_main should be empty and load default fragment in the navigation file.

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
I think if you create fragment lista and fragment_second you should keep this as empty.

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/res/layout/fragment_second.xml
> +        app:layout_constraintTop_toTopOf="parent" />
You should use app:layout_constraintTop_toBottomOf property like you did in fragment_lista, that way you use Constraint layout properly.

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
I see what you were trying to set up here... The Fragment NavigationHost. 
This is the proper fragment... 
`<fragment
        android:id="@+id/nav_host_fragment"
        android:name="androidx.navigation.fragment.NavHostFragment"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:defaultNavHost="true"
        app:navGraph="@navigation/nav_graph" />`

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
and then in the MainActivity Class should look like this one.
`class MainActivity : AppCompatActivity() {
    lateinit var navController: NavController
    lateinit var navHostFragment: NavHostFragment
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        navHostFragment = supportFragmentManager.findFragmentById(R.id.nav_host_fragment) as NavHostFragment
        navController = navHostFragment.navController
    }
}`

2020-08-02 19:06 UTC, williamgdev commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
Here in this PR you should see the changes. Feel free to merge it into your branch or copy and paste 😊
https://github.com/amaurycb/AppEmpty/pull/8

2020-08-03 19:49 UTC, amaurycb commented on app/src/main/java/com/example/appempty/SecondFragment.kt
> +private const val ARG_PARAM1 = "param1"
these arg are generated whith the creation of the  fragment file.

2020-08-04 06:45 UTC, williamgdev approved these changes

2020-08-04 06:45 UTC, merged